# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Regolith Linux
email: kgilmer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Regolith Linux is a Linux distribution focused on user productivity.
  Using Ubuntu as a foundation and Gnome's system management facilities,
  Regolith utilizes the i3wm tiling window management approach that keeps the
  user's screen clutter free yet offering powerful features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://regolith-linux.org"
twitter_username: kgilmer
github_username:  kgilmer

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
